### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by FPS-86** [VanillaPlusPlus/InfectedHordes#1]
Hi! I have an error when adding this script

Can't compile mission init script'!
```
$CurrentDir:mpmissions\dayzOffline.chernarusplus\init.c(84): Bad type 'InfectedHordesPlusSpawner'

Runtime mode
CLI params: dologs  adminlog  freezecheck  connect 92.53.64.145 port 2402 config ServerProfilesFolder\serverDZ.cfg cfg ServerProfilesFolder\basic.cfg scrAllowFileWrite  profiles ServerProfilesFolder mod @RPCFramework;@Permissions-Framework;@Community-Online-Tools;@Trader;@bT_Map;@BuildAnywhere;@DisableBaseDestruction;@KillFeed;@NewNVG_Borland;@SQUAD MSF-C;@Mass'sManyItemOverhaul(W.I.P);@OP_BaseItems; user 38 scriptDebug true 
```
My init.c https://pastebin.com/X7c6DTij

**Comment by GravityWolfNotAmused** [comment]
You haven't included the InfectedHordeSpawner.c in your init file.

**Comment by GravityWolfNotAmused** [comment]
The only time you will ever see bad type in DayZ is if there is a missing include, I am here to see this issue all the way through, so please let me know if a problem happens after.

**Comment by GravityWolfNotAmused** [comment]
@Irkutsk38 This is my fault for forgetting to add that to the readme before pushing x.x I added to both supply drop and infected hordes.

Close your ticket at anytime you have fixed your issue.

**Comment by FPS-86** [comment]
OK. Thank you. But now this gives an error

$CurrentDir:mpmissions\dayzOffline.chernarusplus\init.c(1): Can't find file '$CurrentDir://mpmissions//dayzOffline.chernarusplus//ServerAddons//InfectedHordesPlus//InfectedHordesPlus.c'

**Comment by GravityWolfNotAmused** [comment]
I just fixed the includes from the other files, please download the files and replace them. I am so sorry. x.x

**Comment by Sniy** [comment]
Now this : $CurrentDir://mpmissions//DayZOffline.chernarusplus//InfectedHordesPlus//InfectedHordesPlusSpawner.c(45): Undefined function 'getLootChoices'

**Comment by GravityWolfNotAmused** [comment]
fixed

**Comment by FPS-86** [comment]
Thanks. Theme can be close)

**Comment by GravityWolfNotAmused** [comment]
Welcome @Irkutsk38

**Comment by Sniy** [comment]
One Question , but they don´t drop Loot or ? Thx . Nice work

**Comment by GravityWolfNotAmused** [comment]
@Sniy Zombies should only be dropping default loot, this is because I didn't want to make this addon client side and force others to need another workshop item. If you want to make this addon client side by all means add it.
