### ISSUE TITLE
[BUG]Script reduces total amount of xombies in other areas of the map.

### ISSUE THREAD

**Issue by renegade2k6** [VanillaPlusPlus/InfectedHordes#2]
Love this script, the only problem we are constantly hearing, is that zombies very rarely spawn any more, only via the horde script.

Few Quotes
"Hello. a question: where are the infected? the zombies have disappeared a few days ago."

" Noticed it as well. In many cities the zombies are totally gone. Where army zombies spawn it spawns a few "army" zombies but in normal cities and villages its empty. And hordes I have found in a few cities but not many at all. And it is really cool and all but my fps drops from 90 to around 30-50 when they spawn. And if you shoot a few of them or if you wait long enough they will dissapear for a few minutes and then they will randomly spawn again, and they can spawn at any time."

**Comment by GravityWolfNotAmused** [comment]
Are you reaching the max amount of infected you can have on the server?

**Comment by GravityWolfNotAmused** [comment]
Also, comment out the lines from your mission and restart, check to see if they spawn.

**Comment by Peinful** [comment]
Up your max infected to 1500 in the Global.xml

**Comment by GravityWolfNotAmused** [comment]
@renegade2k6 Do you still have this issue?
