### ISSUE TITLE
SPAWN 1 time, and nothing more

### ISSUE THREAD

**Issue by LArtDesChOiX** [VanillaPlusPlus/InfectedHordes#6]
The first time, the horde spawn imediatly after the restart, all work good... Maybe Z despawn directly but its not a BIG problem, but after that, nothing.. No new spawn, i restart, delete the json, and delete reinstall all your matser folder lol, no new spawn horde !!!

**Comment by GravityWolfNotAmused** [comment]
Post your json

**Comment by GravityWolfNotAmused** [comment]
if despawn is set to 0 they have to be all killed off before they are removed.

**Comment by LArtDesChOiX** [comment]
```
{
    "INT_MAX_ZOMBIES": 125,
    "INT_MIN_ZOMBIES": 65,
    "INT_INFECTEDHORDE_TIME": 10,
    "INT_INFECTEDHORDE_DESPAWNTIME": 100,
    "MAX_HORDES": 10,
    "SENDBROADCASTMESSAGE": 1,
    "CANSPAWNSPECIALINFECTED": 1,
    "m_HordePositions": {
        "Zelenogorsk South": [
            2572,
            0,
            5105
        ],
        "NWAFC": [
            4823,
            0,
            10457
        ],
        "Novaya Petrovka": [
            3395,
            0,
            13013
        ],
        "Svetlojarsk": [
            13900,
            0,
            13258
        ],
        "Cherno City Centre": [
            6649,
            0,
            2710
        ],
        "NWAFN": [
            4214,
            0,
            10977
        ],
        "NWAFS": [
            4540,
            0,
            9645
        ],
        "Berezino South": [
            11991,
            0,
            9116
        ],
        "Balota Air Strip": [
            4467,
            0,
            2496
        ],
        "Zelenogorsk North": [
            2741,
            0,
            5416
        ],
        "Berezino North": [
            12823,
            0,
            10078
        ],
        "Cherno West": [
            6374,
            0,
            2361
        ],
        "Berezino City Centre": [
            12319,
            0,
            9530
        ],
        "Elektro West": [
            10077,
            0,
            1988
        ],
        "Stary": [
            6046,
            0,
            7733
        ],
        "Cherno East": [
            7331,
            0,
            2850
        ],
        "Vybor": [
            3784,
            0,
            8923
        ],
        "Severograd": [
            8428,
            0,
            12767
        ],
        "Elektro East": [
            10553,
            0,
            2313
        ]
    }
}
```

**Comment by GravityWolfNotAmused** [comment]
I didn't change anything about how they spawn though x.x
Only one spawns, or all of them? Do they despawn?

**Comment by GravityWolfNotAmused** [comment]
This all is printed inside of your scripts.log file

**Comment by LArtDesChOiX** [comment]
Well, at the restart I saw several messages, I teleported, the hordes was there, I killed it, and nothing

**Comment by GravityWolfNotAmused** [comment]
Okay, so if you kill it and it had a despawn time you still have to wait for it's life time to be over, otherwise set despawn time to 0 inside of json.

**Comment by LArtDesChOiX** [comment]
many:

 Horde spawned at <13900.000000, 0.000000, 13258.000000> has lived it's life and depsawned.

**Comment by LArtDesChOiX** [comment]
3 or 4 same message in the sript

**Comment by GravityWolfNotAmused** [comment]
That's because respawn time is probably set to 100 seconds, and it's way too short of a life time. It's always best to set that to 0.

**Comment by LArtDesChOiX** [comment]
i wait 3 hours before message you ^^, wait and nothing

**Comment by LArtDesChOiX** [comment]
Okey i try

**Comment by GravityWolfNotAmused** [comment]
```json
    "INT_INFECTEDHORDE_TIME": 10,
    "INT_INFECTEDHORDE_DESPAWNTIME": 0,
```

**Comment by GravityWolfNotAmused** [comment]
Please @LArtDesChOiX I always want you to put these issues in. I pay attention to my github notification, and I always expect someone to find an issue. So, the sooner I fix the sooner everyone has a better mod.

**Comment by GravityWolfNotAmused** [comment]
Do not hesitate to submit a issue, I am always watching.

**Comment by LArtDesChOiX** [comment]
The hordes works, it's the messages that do not work apparently, I'm falling on a

**Comment by GravityWolfNotAmused** [comment]
the messages? They should be.

**Comment by GravityWolfNotAmused** [comment]
which messages?

**Comment by GravityWolfNotAmused** [comment]
I mean, I don't think I added one of when a horde is killed off, I could do that for helpfulness.
