### ISSUE TITLE
[FEATURE REQUEST] Loot Drop

### ISSUE THREAD

**Issue by Peinful** [VanillaPlusPlus/InfectedHordes#8]
**Is your feature request related to a problem? Please describe.**
Not a problem, but for sure would be cool to have a "LootDrop" variable where we can define what kind of items infected drop from the horde rather than having to change our normal infected held items, this makes killing more infected more rewarding outside of hordes in order to lessen risk.

**Describe the solution you'd like**
Allow server owners to define what kind of loot drops/spawns around dead infected from the horde.

**Comment by GravityWolfNotAmused** [comment]
Peinful,
Thank you for another good suggestion; however, if I were to do that I would have to spawn a bunch of items on the ground with the zombies. Spawning loot on a infected is something that has to be done on client, and that defeats the purpose of being completely server side. I built this for others to build on top of their already made server mission, not to flood the steam workshop with duplicate mods.
